# Generated by Django 5.2 on 2025-04-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gemini API Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
